{% set name = "bit-pop" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/mladenpop-oss/bit-pop/releases/download/v{{ version }}/bit-pop-x86_64-linux.tar.gz"
  sha256: "d9fe77d533287f5e001182c2125fa4e28f6267f2df562fd5fc60a5b0f1f0c400"

about:
  home: "https://github.com/mladenpop-oss/bit-pop"
  license: "MIT"
  license_file: LICENSE
  summary: "Ultra-fast multi-genome DNA read classification"
  doc_url: "https://github.com/mladenpop-oss/bit-pop"

dependencies:
  - openssl
  - zlib

extra:
  recipe-maintainers:
    - mladenpop-oss
